#!/usr/bin/env python3
"""Generate src/ui/banana_icon.h — 28x28 ARGB8888 banana pixel art."""
import math, sys, os

W, H = 28, 28

TRANSPARENT  = 0x00000000
YELLOW       = 0xFFFFE000
YELLOW_LIGHT = 0xFFFFF066
BROWN        = 0xFF7B4400

pixels = [TRANSPARENT] * (W * H)

def set_px(x, y, color):
    if 0 <= x < W and 0 <= y < H:
        pixels[y * W + x] = color

# Banana body: thick circular arc, centre off the lower-right corner so the
# arc curves from upper-right down to lower-left (classic banana orientation).
cx, cy   = 32.0, 32.0
r_outer  = 34.0
r_inner  = 26.0
A_START  = -155.0   # angle (deg) of the lower/left tip
A_END    =  -50.0   # angle (deg) of the upper/right tip

for y in range(H):
    for x in range(W):
        dx, dy = x - cx, y - cy
        r = math.hypot(dx, dy)
        if r_inner <= r <= r_outer:
            angle = math.degrees(math.atan2(dy, dx))
            if A_START <= angle <= A_END:
                set_px(x, y, YELLOW)

# Lighter highlight stripe along the inner edge
for y in range(H):
    for x in range(W):
        dx, dy = x - cx, y - cy
        r = math.hypot(dx, dy)
        if r_inner + 2.5 <= r <= r_outer - 2.5:
            angle = math.degrees(math.atan2(dy, dx))
            if A_START + 5 <= angle <= A_END - 5:
                set_px(x, y, YELLOW_LIGHT)

# Brown tips: pixels within TIP_DEG degrees of each arc endpoint
TIP_DEG = 8.0
for y in range(H):
    for x in range(W):
        if pixels[y * W + x] in (YELLOW, YELLOW_LIGHT):
            dx, dy = x - cx, y - cy
            angle = math.degrees(math.atan2(dy, dx))
            if angle <= A_START + TIP_DEG or angle >= A_END - TIP_DEG:
                set_px(x, y, BROWN)

out = os.path.join(os.path.dirname(__file__), '..', 'src', 'ui', 'banana_icon.h')
with open(out, 'w') as f:
    f.write('/* banana_icon.h — auto-generated by tools/gen_banana.py; do not edit */\n')
    f.write('#ifndef BANANA_ICON_DATA_H\n#define BANANA_ICON_DATA_H\n')
    f.write('#include <stdint.h>\n')
    f.write(f'#define BANANA_ICON_W {W}\n')
    f.write(f'#define BANANA_ICON_H {H}\n')
    f.write(f'static const uint32_t banana_icon_pixels[{W * H}] = {{\n')
    for i, px in enumerate(pixels):
        if i % W == 0:
            f.write('   ')
        f.write(f' 0x{px:08X}u,')
        if i % W == W - 1:
            f.write('\n')
    f.write('};\n#endif /* BANANA_ICON_DATA_H */\n')

print(f'wrote {out}', file=sys.stderr)
